FROM python:3.8.5-alpine3.12

RUN mkdir /usr/src/backproject

WORKDIR /usr/src/backproject

COPY . /usr/src/backproject

RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev \
    && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev \
    openjpeg-dev tiff-dev tk-dev tcl-dev \
    && apk add libffi-dev py-cffi \
    && apk add gettext \
    && pip install --upgrade pip \
    && pip install -r requirements/prod.txt
